services:
  chromium:
    image: lscr.io/linuxserver/chromium:latest
    container_name: chromium
    security_opt:
      - seccomp:unconfined
    environment:
      - CUSTOM_USER=xxxxxxxxxx
      - PASSWORD=xxxxxxxxxxxxx
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
      - PROXY_SERVER=http-https-socks5
    volumes:
      - /root/chrome/config:/config
    ports:
      - 3030:3000  # VNC
      - 3031:3001  # WebRTC
    shm_size: "1gb"
    restart: unless-stopped
    command: >
      /bin/sh -c "
      /usr/bin/chromium-browser \
        --no-sandbox \
        --disable-dev-shm-usage \
        --proxy-server=\"$$PROXY_SERVER\" \
        --enable-remote-extensions \
        --ignore-certificate-errors \
        --no-first-run \
        --no-default-browser-check \
        --user-agent=\"Mozilla/5.0 (Windows NT 10.0; Win64; x64) Chrome/114.0.5735.198\" \
        --kiosk"
