services:
  xfce-desktop:
    image: accetto/ubuntu-vnc-xfce:latest
    container_name: xfce-desktop
    restart: unless-stopped
    ports:
      - "8080:5901" # VNC access (for VNC clients)
      - "8081:6901" # Web access (via browser)
    environment:
      - VNC_RESOLUTION=1280x720
      - VNC_PW=admin
      - ENABLE_VNC_AUDIO=true
      - ENABLE_VNC_COPY=true
      - ENABLE_VNC_PASTE=true
    volumes:
      - xfce-data:/home/headless
      - ./downloads:/home/headless/Downloads
      - ./chrome.desktop:/home/headless/Desktop/google-chrome.desktop
      - ./chrome.desktop:/usr/share/applications/google-chrome.desktop
      - ./install-chrome.sh:/tmp/install-chrome.sh  # Auto-install script
    shm_size: 2gb
    networks:
      - desktop-network
    command: >
      sh -c "
      chmod +x /tmp/install-chrome.sh &&
      /tmp/install-chrome.sh &&
      /dockerstartup/vnc_startup.sh
      "

volumes:
  xfce-data:
    driver: local

networks:
  desktop-network:
    driver: bridge
