services:
  xfce-desktop:
    image: accetto/ubuntu-vnc-xfce:latest
    container_name: xfce-desktop
    restart: unless-stopped
    ports:
      - "8080:5901"  # VNC access
      - "8081:6901"  # Web access
    environment:
      - VNC_RESOLUTION=1280x720 # For the best 1920x1080
      - VNC_PW=xxxxxx
      - ENABLE_VNC_AUDIO=true
      - ENABLE_VNC_COPY=true
      - ENABLE_VNC_PASTE=true
    volumes:
      - xfce-data:/home/headless
      - ./downloads:/home/headless/Downloads
    shm_size: 2gb
    networks:
      - desktop-network

volumes:
  xfce-data:
    driver: local

networks:
  desktop-network:
    driver: bridge
