version : '3.8'

services:
  chromium:
    image: lscr.io/linuxserver/chromium:latest
    container_name: chromium
    security_opt:
      - seccomp:unconfined
    environment:
      - CUSTOM_USER=       # Isi/ubah username favorit
      - PASSWORD=          # Isi/ubah password favorit  
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin # ubah lokal jam sesuai server/vps
      - CHROME_CLI=https://github.com/arcxteam  # opsi
    volumes:
      - /root/chromium/config:/config
    ports:
      - 3010:3000   # Ubah 3010 port favorit (opsi jika bentrok)
      - 3011:3001   # Ubah 3011 port favorit (opsi jika bentrok)
    shm_size: "1gb"
    mem_limit: "2g"    # Membatasi penggunaan RAM maksimum menjadi 2GB
    cpus: "1"          # Membatasi penggunaan CPU maksimal 100% dari satu core
    restart: unless-stopped

    # Konfigurasi pemeriksaan pantau kesehatan kontainer
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]  # cek inferensi aja
      interval: 10m         # Ubah sesuai kemauan 1-60 menit
      timeout: 10s          
      retries: 3            
      start_period: 30s     